[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.69"
axum = "0.6.18"
chumsky = "0.9.2"
clap = { version = "4.3.11", features = ["derive"] }
notify = "6.0.1"
serde = "1.0.166"
serde_json = "1.0.99"
#serde_traitobject = "0.2.8"
socketioxide = "0.3.0"
tokio = "1.29.1"
