[package]
name = "ast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.69"
chumsky = "0.9.2"
serde = { version = "1.0.166", features = ["rc", "derive"] }
serde_json = "1.0.99"
